version: '3'

services:
    redis_master:
        image: redis:4.0.10-alpine

    redis_slave:
        image: redis:4.0.10-alpine
        command: redis-server --slaveof redis_master 6379
        depends_on:
            - redis_master

    sentinel:
        build: .
        image: redis-sentinel
        environment:
            - MASTER_NAME=mymaster
            - QUORUM=1
            - MASTER=redis_master
        depends_on:
            - redis_master
